version: '3.3'

services:
  app:
    build:
      args:
        user: odko
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: darts-image
    container_name: darts-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
    networks:
      - dartsNetwork

  nginx:
    image: nginx:1.17-alpine
    container_name: darts-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - dartsNetwork

networks:
  dartsNetwork:
    driver: bridge
